"""Generate Obsidian index file with all commands."""

from __future__ import annotations

import sqlite3
from datetime import datetime
from pathlib import Path

from terminalsensei.obsidian.writer import sanitize_filename


class IndexGenerator:
    """Generates and maintains the Obsidian _index.md file."""

    def __init__(self, index_path: str | Path):
        """
        Initialize index generator.

        Args:
            index_path: Path to _index.md file
        """
        self.index_path = Path(index_path)

    def generate_index(self, conn: sqlite3.Connection) -> str:
        """
        Generate complete index from database.

        Args:
            conn: SQLite connection

        Returns:
            Markdown content for index
        """
        # Get all commands ordered by usage
        rows = conn.execute(
            """
            SELECT name, usage_count, last_used
            FROM commands
            ORDER BY usage_count DESC, last_used DESC
            """
        ).fetchall()

        lines = []

        # Header
        lines.append("# TerminalSensei CLI Book")
        lines.append("")
        lines.append("*Your personal command reference, automatically updated.*")
        lines.append("")
        lines.append(f"Last synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")

        if not rows:
            lines.append("No commands tracked yet. Start using your terminal!")
            return "\n".join(lines)

        lines.append(f"**Total Commands**: {len(rows)}")
        lines.append("")

        # Section 1: Top Commands (by usage)
        lines.append("## 🏆 Top Commands (by frequency)")
        lines.append("")
        for i, (name, usage_count, _) in enumerate(rows[:15], 1):
            safe_name = sanitize_filename(name)
            lines.append(f"{i}. [[Commands/{safe_name}|{name}]] — {usage_count} uses")
        lines.append("")

        # Section 2: All Commands (alphabetical order)
        lines.append("## 📖 All Commands (A-Z)")
        lines.append("")
        sorted_rows = sorted(rows, key=lambda x: x[0].lower())
        for name, usage_count, _ in sorted_rows:
            safe_name = sanitize_filename(name)
            lines.append(f"- [[Commands/{safe_name}|{name}]] — {usage_count} uses")
        lines.append("")

        # Section 3: Least Used Commands
        lines.append("## 📉 Least Used Commands (bottom 10)")
        lines.append("")
        least_used = sorted(rows, key=lambda x: x[1])[:10]
        for name, usage_count, _ in least_used:
            safe_name = sanitize_filename(name)
            lines.append(f"- [[Commands/{safe_name}|{name}]] — {usage_count} uses")
        lines.append("")

        # Recent mistakes
        mistakes = conn.execute(
            """
            SELECT wrong_command, corrected_command, timestamp
            FROM mistakes
            ORDER BY timestamp DESC
            LIMIT 5
            """
        ).fetchall()

        if mistakes:
            lines.append("## ⚠️ Recent Mistakes")
            lines.append("")
            for wrong, corrected, ts in mistakes:
                from datetime import datetime as dt

                ts_str = dt.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
                if corrected:
                    lines.append(f"- `{wrong}` → `{corrected}` ({ts_str})")
                else:
                    lines.append(f"- `{wrong}` ({ts_str})")
            lines.append("")

        lines.append("---")
        lines.append("Generated by TerminalSensei")

        return "\n".join(lines)

    def update_index(self, conn: sqlite3.Connection) -> None:
        """
        Update the index file.

        Args:
            conn: SQLite connection
        """
        self.index_path.parent.mkdir(parents=True, exist_ok=True)
        content = self.generate_index(conn)
        self.index_path.write_text(content, encoding="utf-8")
